### ISSUE TITLE
Create a data class for both QuizCategory and QuizQuestions

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quiz-App-React-Native#2]
To store and use the data from api we need two data class which will be used later. Your task is to implement 2 data class

For data types of responses and structures for quiz refer to this [API](https://rapidapi.com/tethertechnologies095/api/trivia-questions-api)
- In 'models' folder create a data class named 'QuizCategory' 
- In 'models' folder create a data class name 'QuizQuestions'

**Comment by Abdullah17m** [comment]
Hi @parjanya-rajput can you assign me this issue, i would like to work on this issue.

**Comment by parjanya-rajput** [comment]
I’ve assigned you the issue, do remember to name classes appropriately and comment wherever necessary

**Comment by Abdullah17m** [comment]
Hi @parjanya-rajput I've Created 2 data classes and i am adding a PR please look into it if it is correct.
