### ISSUE TITLE
Design a Question Page that will display Question with options

### ISSUE THREAD

**Issue by parjanya-rajput** [MSTC-DA-IICT/Hacktoberfest24-Quiz-App-React-Native#4]
Design a screen named QuestionScreen which will display the Quiz question, it's difficulty and 4 options.

For more info about data class/fields refer to 'models' folder or this [API](https://rapidapi.com/tethertechnologies095/api/trivia-questions-api)

**Comment by aaryak1369** [comment]
I would like to give this a go, can you assign this issue to me?

**Comment by parjanya-rajput** [comment]
ok, we're assigning it to you

**Comment by aaryak1369** [comment]
Can you please guide me on what you would like...
1. Once a user selects a wrong option, do you want the user to be able to select again? or just show the correct answer?
2. If user selects correct answer on first try then do you want the user to have an option to attempt another quiz question right away or have a button to render new question?

**Comment by parjanya-rajput** [comment]
1. If the user selects the wrong option just show the right answer directly
2. If right answer is selected on first try then display a message like "Good Job" and then next question button should be visible

**Comment by parjanya-rajput** [comment]
what's the status on your PR? Are you facing any issues

**Comment by aaryak1369** [comment]
I have the basic logic implemented using a set of sample data. Now just trying to integrate the api.
Shall i create a pull request without api integration?
<img height="480"  src="https://github.com/user-attachments/assets/35889b0c-c99f-4d49-b5c2-7c05a3baab91"/>
<img height="480" src="https://github.com/user-attachments/assets/345e5bb1-8a5f-4742-b3f1-633479cc9d8a"/>

**Comment by parjanya-rajput** [comment]
The issue states only for creating the design not the API integration that will be another issue in itself. So you can make a PR with a static strings or some kind of json list as you wish!

**Comment by aaryak1369** [comment]
Thank you!
I have opened a pull request. Please check it out.

**Comment by parjanya-rajput** [comment]
Great work! I have merged the pull request and everything is working!
